var cart = {}; var currentCat = 'all'; var currentSearch = '';
function saveCart() { try { localStorage.setItem('uonni_cart', JSON.stringify(cart)); } catch (e) { } }
function loadCart() { try { var s = localStorage.getItem('uonni_cart'); if (s) { cart = JSON.parse(s); renderCart(); } } catch (e) { } }
function saveClientData() { var data = { nombre: document.getElementById("f-nombre").value.trim(), negocio: document.getElementById("f-negocio").value.trim(), wa: document.getElementById("f-wa").value.trim(), mail: document.getElementById("f-mail").value.trim(), localidad: document.getElementById("f-localidad").value.trim() }; localStorage.setItem('uonni_client', JSON.stringify(data)); }
function loadClientData() { try { var s = localStorage.getItem('uonni_client'); if (!s) return; var d = JSON.parse(s); if (d.nombre) document.getElementById("f-nombre").value = d.nombre; if (d.negocio) document.getElementById("f-negocio").value = d.negocio; if (d.wa) document.getElementById("f-wa").value = d.wa; if (d.mail) document.getElementById("f-mail").value = d.mail; if (d.localidad) document.getElementById("f-localidad").value = d.localidad; } catch (e) { } }
function fmt(n) { var s = Math.round(n).toString(); var r = ""; var c = 0; for (var i = s.length - 1; i >= 0; i--) { if (c > 0 && c % 3 === 0) r = "." + r; r = s[i] + r; c++; } return "$" + r; }
function qch(id, d) { var inp = document.getElementById(id); if (!inp) return; var v = parseInt(inp.value) || 0; v = Math.max(0, v + d); inp.value = v; }
function addToCart(id) { var inp = document.getElementById(id); if (!inp) return; var qty = parseInt(inp.value) || 0; if (qty <= 0) { inp.value = 1; qty = 1; } var name = inp.getAttribute("data-name"); var price = parseInt(inp.getAttribute("data-price")); if (cart[id]) { cart[id].qty += qty; } else { cart[id] = { name: name, price: price, qty: qty }; } var btn = document.getElementById("btn_" + id); if (btn) { btn.textContent = "Agregado"; btn.classList.add("success"); setTimeout(function () { btn.textContent = "+ Agregar"; btn.classList.remove("success"); }, 1400); } var card = document.getElementById("card_" + id); if (card) { card.classList.add("added-flash"); setTimeout(function () { card.classList.remove("added-flash"); }, 1400); } inp.value = 0; renderCart(); saveCart(); }
function removeFromCart(id) { delete cart[id]; renderCart(); saveCart(); }
function renderCart() { var body = document.getElementById("cart-items"); var keys = Object.keys(cart); var total = 0, totalQty = 0; if (keys.length === 0) { body.innerHTML = '<div class="cart-empty"><div style="font-size:40px;margin-bottom:8px">&#128722;</div>Todavia no agregaste productos.</div>'; updateTotal(0); document.getElementById("cart-badge").textContent = "0"; document.getElementById("cart-total-header").textContent = "$0"; return; } var html = ""; for (var i = 0; i < keys.length; i++) { var item = cart[keys[i]]; var sub = item.price * item.qty; total += sub; totalQty += item.qty; html += '<div class="cart-item"><div class="ci-info"><div class="ci-name">' + item.name + '</div><div class="ci-detail">' + item.qty + ' u. x ' + fmt(item.price) + '</div></div><div style="display:flex;align-items:center;gap:8px"><div class="ci-subtotal">' + fmt(sub) + '</div><button class="ci-remove" data-id="' + keys[i] + '" onclick="removeFromCart(this.dataset.id)">&#215;</button></div></div>'; } body.innerHTML = html; updateTotal(total); document.getElementById("cart-badge").textContent = totalQty; document.getElementById("cart-total-header").textContent = fmt(total); }
function updateTotal(total) { document.getElementById("total-display").textContent = fmt(total); var pct = Math.min(100, (total / 300000) * 100); document.getElementById("minimo-fill").style.width = pct + "%"; var msg = document.getElementById("minimo-msg"); var btn = document.getElementById("btn-confirmar"); if (total >= 300000) { msg.textContent = "Minimo alcanzado"; msg.className = "minimo-msg ok"; btn.disabled = false; } else { var falta = 300000 - total; msg.textContent = "Faltan " + fmt(falta) + " para el minimo"; msg.className = "minimo-msg no"; btn.disabled = true; } }
function openCart() { document.getElementById("cart-overlay").classList.add("open"); document.getElementById("cart-panel").classList.add("open"); document.body.style.overflow = "hidden"; }
function closeCart() { document.getElementById("cart-overlay").classList.remove("open"); document.getElementById("cart-panel").classList.remove("open"); document.body.style.overflow = ""; }
function doSearch(val) { currentSearch = val.trim().toLowerCase(); document.getElementById("clear-btn").style.display = currentSearch ? "block" : "none"; applyFilters(); }
function clearSearch() { document.getElementById("search-input").value = ""; doSearch(""); }
function filterCat(el, cat) { document.querySelectorAll(".cat-pill").forEach(function (p) { p.classList.remove("active"); }); el.classList.add("active"); currentCat = cat; applyFilters(); }
function applyFilters() { var sections = document.querySelectorAll(".cat-section"); var banners = document.querySelectorAll(".group-banner"); var anyVisible = false; var visibleGroups = {}; sections.forEach(function (sec) { var secCat = sec.getAttribute("data-cat"); var secGroup = sec.getAttribute("data-group"); var catMatch = currentCat === "all" || (currentCat.startsWith("g:") ? secGroup === currentCat.slice(2) : secCat === currentCat); var cards = sec.querySelectorAll(".prod-card"); var secHasVisible = false; cards.forEach(function (card) { var nameMatch = !currentSearch || card.getAttribute("data-name").includes(currentSearch); var visible = catMatch && nameMatch; card.style.display = visible ? "" : "none"; if (visible) secHasVisible = true; }); sec.style.display = secHasVisible ? "" : "none"; if (secHasVisible) { anyVisible = true; visibleGroups[secGroup] = true; } }); banners.forEach(function (b) { b.style.display = visibleGroups[b.getAttribute("data-group")] ? "" : "none"; }); document.getElementById("no-results").style.display = anyVisible ? "none" : "block"; }
function validateForm() { var valid = true;["f-nombre", "f-wa", "f-localidad"].forEach(function (id) { var inp = document.getElementById(id); if (!inp.value.trim()) { inp.classList.add("error"); valid = false; } else { inp.classList.remove("error"); } }); return valid; }
function confirmarPedido() { if (!validateForm()) { document.getElementById("f-nombre").scrollIntoView({ behavior: "smooth", block: "center" }); return; } saveClientData(); var keys = Object.keys(cart); if (keys.length === 0) { alert("Agrega productos primero."); return; } var total = Object.values(cart).reduce(function (s, i) { return s + i.price * i.qty; }, 0); var nombre = document.getElementById("f-nombre").value.trim(); var negocio = document.getElementById("f-negocio").value.trim(); var wa = document.getElementById("f-wa").value.trim(); var mail = document.getElementById("f-mail").value.trim(); var localidad = document.getElementById("f-localidad").value.trim(); var ch = ""; if (nombre) ch += "<b>Nombre:</b> " + nombre + "<br>"; if (negocio) ch += "<b>Negocio:</b> " + negocio + "<br>"; if (wa) ch += "<b>WhatsApp:</b> " + wa + "<br>"; if (mail) ch += "<b>Email:</b> " + mail + "<br>"; if (localidad) ch += "<b>Localidad:</b> " + localidad + "<br>"; document.getElementById("resumen-cliente").innerHTML = ch; var ih = ""; for (var i = 0; i < keys.length; i++) { var item = cart[keys[i]]; var sub = item.price * item.qty; ih += '<div class="modal-item"><div><div class="modal-item-name">' + item.name + '</div><div class="modal-item-qty">' + item.qty + ' u. x ' + fmt(item.price) + '</div></div><div class="modal-item-sub">' + fmt(sub) + '</div></div>'; } document.getElementById("resumen-items").innerHTML = ih; document.getElementById("resumen-total").textContent = fmt(total); document.getElementById("resumen-minimo").textContent = total >= 300000 ? "Minimo alcanzado" : ""; document.getElementById("modal-overlay").classList.add("open"); }
function cerrarModal() { document.getElementById("modal-overlay").classList.remove("open"); }
function buildTextResumen() { var nombre = document.getElementById("f-nombre").value.trim(); var negocio = document.getElementById("f-negocio").value.trim(); var wa = document.getElementById("f-wa").value.trim(); var mail = document.getElementById("f-mail").value.trim(); var localidad = document.getElementById("f-localidad").value.trim(); var total = Object.values(cart).reduce(function (s, i) { return s + i.price * i.qty; }, 0); var fecha = new Date().toLocaleDateString("es-AR", { day: "2-digit", month: "2-digit", year: "numeric" }); var sep = "------------------------"; var lines = []; lines.push("*PEDIDO MAYORISTA UONNI*"); lines.push("Fecha: " + fecha); lines.push(sep); lines.push("*DATOS DEL COMPRADOR*"); if (nombre) lines.push("Nombre: " + nombre); if (negocio) lines.push("Negocio: " + negocio); if (wa) lines.push("WhatsApp: " + wa); if (mail) lines.push("Email: " + mail); if (localidad) lines.push("Localidad: " + localidad); lines.push(sep); lines.push("*PRODUCTOS*"); var keys = Object.keys(cart); for (var i = 0; i < keys.length; i++) { var item = cart[keys[i]]; lines.push("- " + item.name); lines.push("  " + item.qty + " u. x " + fmt(item.price) + " = " + fmt(item.price * item.qty)); } lines.push(sep); lines.push("*TOTAL: " + fmt(total) + "*"); return lines.join("\n"); }
function copiarResumen() { var txt = buildTextResumen(); navigator.clipboard.writeText(txt).then(function () { var btn = document.getElementById("btn-copiar"); btn.textContent = "Copiado!"; setTimeout(function () { btn.textContent = "Copiar"; }, 2000); }).catch(function () { alert("No se pudo copiar automaticamente."); }); }
function enviarWA() { var txt = buildTextResumen(); window.open("https://wa.me/541121733672?text=" + encodeURIComponent(txt), "_blank"); }
// Drag scroll en el menu de categorias
var slider = document.querySelector('.cats-scroll');
var isDown = false;
var startX;
var scrollLeft;

slider.addEventListener('mousedown', function(e) {
  isDown = true;
  slider.style.cursor = 'grabbing';
  startX = e.pageX - slider.offsetLeft;
  scrollLeft = slider.scrollLeft;
});
slider.addEventListener('mouseleave', function() {
  isDown = false;
  slider.style.cursor = 'grab';
});
slider.addEventListener('mouseup', function() {
  isDown = false;
  slider.style.cursor = 'grab';
});
slider.addEventListener('mousemove', function(e) {
  if (!isDown) return;
  e.preventDefault();
  var x = e.pageX - slider.offsetLeft;
  var walk = (x - startX) * 1.5;
  slider.scrollLeft = scrollLeft - walk;
});loadCart(); loadClientData(); updateTotal(0);
